### ISSUE TITLE
Required checkbox

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/ClubExcellence#30]
Please remove "Required" checkbox on task creation except for USAH and CX admin

**Comment by sn-np** [comment]
Fixed

**Comment by cameroneickmeyer** [comment]
·        30 – logged in as secretary (non-admin) in the 17-18 season for TST0001, created a new task and the required checkbox still appears; logged in as brittany.bobak (Test Position #3, non-admin) for the 17-18 season in TST0001, the required checkbox still appears.
